#!/usr/bin/env python3
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Generate a weekly GCP cost analysis report as Markdown."""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import cost_breakdown
import top_changes
from _bq import (
    BQError,
    DEFAULT_PROJECT,
    build_cost_type_clause,
    date_range_from_args,
    describe_project_scope,
    expand_reference_periods,
    format_currency,
    format_delta,
    format_percent,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

DEFAULT_BEDROCK_REPO = Path("/Users/lukemauldin/code/github.com/KidStrong/KidStrongBedrock")
DEFAULT_TERRAFORM_REPO = Path("/Users/lukemauldin/code/github.com/KidStrong/tf-main-apps")


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point. Returns exit code."""
    args = parse_args(argv)

    try:
        run(args)
        return 0
    except KeyboardInterrupt:
        return 130
    except BQError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"ERROR: Unexpected error: {e}", file=sys.stderr)
        return 1


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--target-start", "-ts", required=True,
                        help="Target period start date (YYYY-MM-DD)")
    parser.add_argument("--target-end", "-te", required=True,
                        help="Target period end date (YYYY-MM-DD)")
    parser.add_argument("--reference-start", "-rs",
                        help="Reference period start date (YYYY-MM-DD)")
    parser.add_argument("--reference-end", "-re",
                        help="Reference period end date (YYYY-MM-DD)")
    parser.add_argument("--baseline-periods", type=int, default=1,
                        help="Number of prior periods to average for reference (default: 1)")
    parser.add_argument("--normalize-per-day", action="store_true",
                        help="Normalize costs by days in period")
    parser.add_argument("--project-filter", "-p",
                        help="Filter billed costs to a specific project.id in the export")
    parser.add_argument("--bq-project", default=DEFAULT_PROJECT,
                        help=(
                            "GCP project that runs the BigQuery query and hosts the billing "
                            f"dataset access (default: {DEFAULT_PROJECT}); not a cost filter"
                        ))
    parser.add_argument("--cost-type", action="append", dest="cost_types",
                        help="Include only specific cost_type (repeatable)")
    parser.add_argument("--exclude-cost-type", action="append", dest="exclude_cost_types",
                        help="Exclude specific cost_type (repeatable)")
    parser.add_argument("--exclude-tax-adjustments", action="store_true",
                        help="Exclude tax and adjustment cost types")
    parser.add_argument("--limit", "-l", type=int, default=5,
                        help="Max rows to show in tables (default: 5)")
    parser.add_argument("--output", "-o", type=Path,
                        help="Output Markdown path (default: autogenerated)")
    parser.add_argument("--skip-revisions", action="store_true",
                        help="Skip Cloud Run revision summary")
    parser.add_argument("--skip-git", action="store_true",
                        help="Skip git change summaries")
    parser.add_argument("--skip-job-executions", action="store_true",
                        help="Skip Cloud Run job execution counts")
    parser.add_argument("--revision-limit", type=int, default=100,
                        help="Max Cloud Run revisions to show (default: 100)")
    parser.add_argument("--git-limit", type=int, default=50,
                        help="Max git commits to show (default: 50)")
    parser.add_argument("--bedrock-repo", type=Path, default=DEFAULT_BEDROCK_REPO,
                        help="Path to KidStrongBedrock repo")
    parser.add_argument("--terraform-repo", type=Path, default=DEFAULT_TERRAFORM_REPO,
                        help="Path to tf-main-apps repo")

    return parser.parse_args(argv)


def run_script(script_path: Path, args: list[str]) -> str:
    """Run a sibling script and capture stdout."""
    cmd = [sys.executable, str(script_path)] + args
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        stderr = result.stderr.strip()
        return f"ERROR running {script_path.name}: {stderr}" if stderr else "ERROR running script."
    return result.stdout.strip()


def format_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    """Return Markdown table lines."""
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def run(args: argparse.Namespace) -> None:
    """Generate report and write to output path."""
    if args.baseline_periods < 1:
        raise ValueError("--baseline-periods must be >= 1")

    target, reference = date_range_from_args(
        args.target_start,
        args.target_end,
        args.reference_start,
        args.reference_end,
    )
    reference_periods = expand_reference_periods(reference, args.baseline_periods)
    cost_type_clause = build_cost_type_clause(
        args.cost_types,
        args.exclude_cost_types,
        args.exclude_tax_adjustments,
    )

    service_raw = cost_breakdown.query_by_service(
        target,
        reference_periods,
        args.project_filter,
        cost_type_clause,
        bq_project=args.bq_project,
    )
    service_rows = cost_breakdown.compute_metrics(
        service_raw,
        baseline_periods=args.baseline_periods,
        reference_days=reference.days,
        target_days=target.days,
        normalize_per_day=args.normalize_per_day,
    )
    service_rows.sort(key=lambda r: r["delta"], reverse=True)

    total_ref_net = sum(r.get("reference_net", 0.0) for r in service_rows)
    total_target_net = sum(r.get("target_net", 0.0) for r in service_rows)
    total_delta = total_target_net - total_ref_net
    pct_change = (total_delta / total_ref_net * 100) if total_ref_net > 0 else None

    top_services = [r.get("dimension", "") for r in service_rows if r.get("delta", 0) > 0][:3]
    top_services_str = ", ".join(top_services) if top_services else "No major drivers detected"

    report_lines: list[str] = []
    report_lines.append(f"# GCP Cost Analysis Report")
    report_lines.append("")
    report_lines.append(f"Period: {target.start_str} to {target.end_str}")
    if args.baseline_periods > 1:
        report_lines.append(
            f"Reference: {reference.start_str} to {reference.end_str} (avg of {args.baseline_periods})"
        )
    else:
        report_lines.append(f"Reference: {reference.start_str} to {reference.end_str}")
    if args.normalize_per_day:
        report_lines.append("Mode: Per-day normalization enabled")
    report_lines.append(f"Project scope: {describe_project_scope(args.project_filter)}")
    report_lines.append(f"BigQuery host project: {args.bq_project}")
    if args.cost_types:
        report_lines.append(f"Cost types: include only {', '.join(args.cost_types)}")
    elif args.exclude_cost_types or args.exclude_tax_adjustments:
        exclude = (args.exclude_cost_types or []) + (
            ["tax", "adjustment"] if args.exclude_tax_adjustments else []
        )
        report_lines.append(f"Cost types: excluding {', '.join(exclude)}")
    report_lines.append("")

    report_lines.append("## Executive Summary")
    summary = (
        f"Net change {format_delta(total_delta)}"
        + (f" ({format_percent(pct_change)})" if pct_change is not None else "")
        + f" vs baseline average. Top drivers: {top_services_str}."
    )
    report_lines.append(summary)
    report_lines.append("")

    report_lines.append("## Cost Breakdown (Top Services)")
    headers = ["Service", "Reference", "Target", "Delta", "% Change", "Credits Δ"]
    rows = []
    for row in service_rows[:args.limit]:
        rows.append([
            row.get("dimension", "")[:40],
            format_currency(row.get("reference_net")),
            format_currency(row.get("target_net")),
            format_delta(row.get("delta")),
            format_percent(row.get("pct_change")) if row.get("pct_change") is not None else "N/A",
            format_delta(row.get("credits_delta")),
        ])
    report_lines.extend(format_table(headers, rows))
    report_lines.append("")

    report_lines.append("## Top Resource Changes")
    try:
        resource_raw = top_changes.query_resource_changes(
            target,
            reference_periods,
            None,
            args.project_filter,
            max(args.limit, 10),
            cost_type_clause,
            bq_project=args.bq_project,
        )
    except BQError:
        resource_raw = top_changes.query_sku_changes(
            target,
            reference_periods,
            None,
            args.project_filter,
            max(args.limit, 10),
            cost_type_clause,
            bq_project=args.bq_project,
        )

    resource_rows = top_changes.compute_change_rows(
        resource_raw,
        baseline_periods=args.baseline_periods,
        reference_days=reference.days,
        target_days=target.days,
        normalize_per_day=args.normalize_per_day,
    )
    resource_rows = [r for r in resource_rows if r.get("delta", 0) > 0]
    resource_rows.sort(key=lambda r: r["delta"], reverse=True)

    res_headers = ["Service/SKU", "Resource", "Reference", "Target", "Delta", "% Change", "Credits Δ"]
    res_rows = []
    for row in resource_rows[:args.limit]:
        resource = row.get("resource_name", "") or "(aggregate)"
        if len(resource) > 40:
            resource = "..." + resource[-37:]
        res_rows.append([
            f"{row.get('service', '')} / {row.get('sku', '')[:30]}",
            resource,
            format_currency(row.get("reference_net")),
            format_currency(row.get("target_net")),
            format_delta(row.get("delta")),
            format_percent(row.get("pct_change")) if row.get("pct_change") is not None else "N/A",
            format_delta(row.get("credits_delta")),
        ])
    report_lines.extend(format_table(res_headers, res_rows))
    report_lines.append("")

    script_dir = Path(__file__).resolve().parent
    if not args.skip_revisions:
        report_lines.append("## Cloud Run Deployments")
        rev_script = script_dir / "cloud_run_revisions.py"
        rev_args = [
            "--start", target.start_str,
            "--end", target.end_str,
            "--all-projects",
            "--limit", str(args.revision_limit),
        ]
        if args.skip_job_executions:
            rev_args.append("--skip-job-executions")
        rev_output = run_script(rev_script, rev_args)
        report_lines.append("```")
        report_lines.append(rev_output)
        report_lines.append("```")
        report_lines.append("")

    if not args.skip_git:
        report_lines.append("## Git Changes")
        git_script = script_dir / "git_deployments.py"
        bedrock_output = run_script(git_script, [
            "--start", target.start_str,
            "--end", target.end_str,
            "--repo", str(args.bedrock_repo),
            "--limit", str(args.git_limit),
        ])
        report_lines.append("### KidStrongBedrock")
        report_lines.append("```")
        report_lines.append(bedrock_output)
        report_lines.append("```")
        report_lines.append("")

        terraform_output = run_script(git_script, [
            "--start", target.start_str,
            "--end", target.end_str,
            "--repo", str(args.terraform_repo),
            "--limit", str(args.git_limit),
            "--filter", "terraform",
        ])
        report_lines.append("### Terraform (tf-main-apps)")
        report_lines.append("```")
        report_lines.append(terraform_output)
        report_lines.append("```")
        report_lines.append("")

    output_path = args.output or Path(
        f"gcp-cost-report-{target.start_str}-to-{target.end_str}.md"
    )
    output_path.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    print(f"Wrote report to {output_path}")


if __name__ == "__main__":
    sys.exit(main())
